from __future__ import annotations

import json
import sqlite3
import threading
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Iterator

from .config_schema import default_config, validate_config
from .settings import database_url


class VersionConflict(RuntimeError):
    pass


class StoreUnavailable(RuntimeError):
    pass


def utc_now() -> datetime:
    return datetime.now(UTC)


def iso_now() -> str:
    return utc_now().isoformat()


class ConfigStore:
    def __init__(self, url: str | None = None) -> None:
        self.url = url or database_url()
        self.postgres = self.url.startswith(("postgresql://", "postgresql+"))
        self._initialized = False
        self._lock = threading.Lock()

    @contextmanager
    def connect(self) -> Iterator[Any]:
        try:
            if self.postgres:
                try:
                    import psycopg
                except ImportError as error:
                    raise StoreUnavailable("PostgreSQL 드라이버가 설치되지 않았습니다.") from error
                connection = psycopg.connect(self.url)
            else:
                prefix = "sqlite:///"
                if not self.url.startswith(prefix):
                    raise StoreUnavailable("지원하지 않는 DATABASE_URL 형식입니다.")
                path = Path(self.url[len(prefix) :])
                path.parent.mkdir(parents=True, exist_ok=True)
                connection = sqlite3.connect(path, timeout=15, check_same_thread=False)
            try:
                yield connection
            finally:
                connection.close()
        except (StoreUnavailable, VersionConflict):
            raise
        except Exception as error:
            raise StoreUnavailable("설정 저장소에 연결할 수 없습니다.") from error

    def execute(self, connection: Any, sql: str, parameters: tuple[Any, ...] = ()) -> Any:
        if self.postgres:
            sql = sql.replace("?", "%s")
        return connection.execute(sql, parameters)

    def ensure_schema(self) -> None:
        if self._initialized:
            return
        with self._lock:
            if self._initialized:
                return
            with self.connect() as connection:
                id_column = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
                self.execute(
                    connection,
                    """
                    CREATE TABLE IF NOT EXISTS app_config (
                        singleton INTEGER PRIMARY KEY,
                        version INTEGER NOT NULL,
                        config_json TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        updated_by TEXT NOT NULL
                    )
                    """,
                )
                self.execute(
                    connection,
                    f"""
                    CREATE TABLE IF NOT EXISTS config_versions (
                        id {id_column},
                        version INTEGER NOT NULL UNIQUE,
                        config_json TEXT NOT NULL,
                        change_note TEXT NOT NULL,
                        created_at TEXT NOT NULL,
                        created_by TEXT NOT NULL
                    )
                    """,
                )
                self.execute(
                    connection,
                    """
                    CREATE TABLE IF NOT EXISTS admin_sessions (
                        token_hash TEXT PRIMARY KEY,
                        csrf_token TEXT NOT NULL,
                        username TEXT NOT NULL,
                        created_at TEXT NOT NULL,
                        expires_at TEXT NOT NULL,
                        last_seen_at TEXT NOT NULL
                    )
                    """,
                )
                self.execute(
                    connection,
                    """
                    CREATE TABLE IF NOT EXISTS schedule_document (
                        singleton INTEGER PRIMARY KEY,
                        version INTEGER NOT NULL,
                        data_json TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        updated_by TEXT NOT NULL
                    )
                    """,
                )
                row = self.execute(connection, "SELECT version FROM app_config WHERE singleton = 1").fetchone()
                if row is None:
                    now = iso_now()
                    encoded = json.dumps(default_config(), ensure_ascii=False, allow_nan=False)
                    self.execute(
                        connection,
                        "INSERT INTO app_config(singleton, version, config_json, updated_at, updated_by) VALUES(1, 1, ?, ?, ?)",
                        (encoded, now, "system"),
                    )
                    self.execute(
                        connection,
                        "INSERT INTO config_versions(version, config_json, change_note, created_at, created_by) VALUES(1, ?, ?, ?, ?)",
                        (encoded, "원본 기준 초기 설정", now, "system"),
                    )
                row = self.execute(connection, "SELECT version FROM schedule_document WHERE singleton = 1").fetchone()
                if row is None:
                    self.execute(
                        connection,
                        "INSERT INTO schedule_document(singleton, version, data_json, updated_at, updated_by) VALUES(1, 1, ?, ?, ?)",
                        (json.dumps({"version": 1, "projects": [], "events": [], "tasks": []}), iso_now(), "system"),
                    )
                connection.commit()
            self._initialized = True

    def current(self) -> dict[str, Any]:
        self.ensure_schema()
        with self.connect() as connection:
            row = self.execute(
                connection,
                "SELECT version, config_json, updated_at, updated_by FROM app_config WHERE singleton = 1",
            ).fetchone()
        if row is None:
            raise StoreUnavailable("현재 설정을 찾을 수 없습니다.")
        return {
            "version": int(row[0]),
            "config": validate_config(json.loads(row[1])),
            "updatedAt": row[2],
            "updatedBy": row[3],
        }

    def schedule_current(self) -> dict[str, Any]:
        self.ensure_schema()
        with self.connect() as connection:
            row = self.execute(
                connection,
                "SELECT version, data_json, updated_at, updated_by FROM schedule_document WHERE singleton = 1",
            ).fetchone()
        if row is None:
            raise StoreUnavailable("일정 데이터를 찾을 수 없습니다.")
        return {"version": int(row[0]), "data": json.loads(row[1]), "updatedAt": row[2], "updatedBy": row[3]}

    def schedule_save(self, data: dict[str, Any], expected_version: int, actor: str) -> dict[str, Any]:
        encoded = json.dumps(data, ensure_ascii=False, allow_nan=False)
        self.ensure_schema()
        now = iso_now()
        with self.connect() as connection:
            cursor = self.execute(
                connection,
                "UPDATE schedule_document SET version = version + 1, data_json = ?, updated_at = ?, updated_by = ? WHERE singleton = 1 AND version = ?",
                (encoded, now, actor, expected_version),
            )
            if cursor.rowcount != 1:
                connection.rollback()
                raise VersionConflict("다른 기기에서 일정이 변경되었습니다. 현재 내용을 확인해 주세요.")
            connection.commit()
        return {"version": expected_version + 1, "data": data, "updatedAt": now, "updatedBy": actor}

    def save(self, config: dict[str, Any], expected_version: int, note: str, actor: str) -> dict[str, Any]:
        validated = validate_config(config)
        clean_note = note.strip()
        if not clean_note or len(clean_note) > 500:
            raise ValueError("변경 설명은 1~500자로 입력해 주세요.")
        encoded = json.dumps(validated, ensure_ascii=False, allow_nan=False)
        self.ensure_schema()
        with self.connect() as connection:
            row = self.execute(connection, "SELECT version FROM app_config WHERE singleton = 1").fetchone()
            current_version = int(row[0]) if row else 0
            if current_version != expected_version:
                raise VersionConflict(f"다른 화면에서 설정이 변경되었습니다. 현재 버전은 {current_version}입니다.")
            next_version = current_version + 1
            now = iso_now()
            self.execute(
                connection,
                "UPDATE app_config SET version = ?, config_json = ?, updated_at = ?, updated_by = ? WHERE singleton = 1",
                (next_version, encoded, now, actor),
            )
            self.execute(
                connection,
                "INSERT INTO config_versions(version, config_json, change_note, created_at, created_by) VALUES(?, ?, ?, ?, ?)",
                (next_version, encoded, clean_note, now, actor),
            )
            connection.commit()
        return {"version": next_version, "config": validated, "updatedAt": now, "updatedBy": actor}

    def versions(self, limit: int = 20) -> list[dict[str, Any]]:
        self.ensure_schema()
        with self.connect() as connection:
            rows = self.execute(
                connection,
                "SELECT version, change_note, created_at, created_by FROM config_versions ORDER BY version DESC LIMIT ?",
                (min(100, max(1, limit)),),
            ).fetchall()
        return [
            {"version": int(row[0]), "note": row[1], "createdAt": row[2], "createdBy": row[3]}
            for row in rows
        ]

    def version(self, version: int) -> dict[str, Any] | None:
        self.ensure_schema()
        with self.connect() as connection:
            row = self.execute(
                connection,
                "SELECT version, config_json, change_note, created_at, created_by FROM config_versions WHERE version = ?",
                (version,),
            ).fetchone()
        if row is None:
            return None
        return {
            "version": int(row[0]),
            "config": validate_config(json.loads(row[1])),
            "note": row[2],
            "createdAt": row[3],
            "createdBy": row[4],
        }

    def create_session(self, token_hash: str, csrf_token: str, username: str, minutes: int) -> dict[str, Any]:
        self.ensure_schema()
        now = utc_now()
        expires = now + timedelta(minutes=minutes)
        with self.connect() as connection:
            self.execute(connection, "DELETE FROM admin_sessions WHERE expires_at <= ?", (now.isoformat(),))
            self.execute(
                connection,
                "INSERT INTO admin_sessions(token_hash, csrf_token, username, created_at, expires_at, last_seen_at) VALUES(?, ?, ?, ?, ?, ?)",
                (token_hash, csrf_token, username, now.isoformat(), expires.isoformat(), now.isoformat()),
            )
            connection.commit()
        return {"username": username, "expiresAt": expires.isoformat(), "csrfToken": csrf_token}

    def session(self, token_hash: str, minutes: int, touch: bool = True) -> dict[str, Any] | None:
        self.ensure_schema()
        now = utc_now()
        with self.connect() as connection:
            row = self.execute(
                connection,
                "SELECT csrf_token, username, created_at, expires_at FROM admin_sessions WHERE token_hash = ?",
                (token_hash,),
            ).fetchone()
            if row is None:
                return None
            expires = datetime.fromisoformat(row[3])
            if expires <= now:
                self.execute(connection, "DELETE FROM admin_sessions WHERE token_hash = ?", (token_hash,))
                connection.commit()
                return None
            if touch:
                expires = now + timedelta(minutes=minutes)
                self.execute(
                    connection,
                    "UPDATE admin_sessions SET expires_at = ?, last_seen_at = ? WHERE token_hash = ?",
                    (expires.isoformat(), now.isoformat(), token_hash),
                )
                connection.commit()
        return {
            "csrfToken": row[0],
            "username": row[1],
            "createdAt": row[2],
            "expiresAt": expires.isoformat(),
        }

    def delete_session(self, token_hash: str) -> None:
        self.ensure_schema()
        with self.connect() as connection:
            self.execute(connection, "DELETE FROM admin_sessions WHERE token_hash = ?", (token_hash,))
            connection.commit()


store = ConfigStore()
